# Generated by Django 3.2 on 2021-04-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_doc', models.FileField(upload_to='')),
                ('student_doc', models.FileField(upload_to='')),
            ],
        ),
    ]
