# Generated by Django 3.2 on 2021-04-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapi', '0003_auto_20210417_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarity',
            name='remark',
        ),
        migrations.AlterField(
            model_name='similarity',
            name='file',
            field=models.FileField(default='', upload_to='algoapi/media/'),
        ),
    ]
