# Generated by Django 3.2 on 2021-04-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyapi', '0006_similarity_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarity',
            name='file2',
        ),
    ]
