# Generated by Django 3.2 on 2021-04-19 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyapi', '0007_remove_similarity_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarity',
            name='file2',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
