# Generated by Django 3.2 on 2021-04-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyapi', '0008_similarity_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarity',
            name='file2',
        ),
    ]
