# Generated by Django 3.2 on 2021-04-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapi', '0009_remove_similarity_file2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='media/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
