# Generated by Django 3.2 on 2021-04-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarity',
            name='remark',
            field=models.CharField(default='', max_length=20),
        ),
    ]
