# Generated by Django 3.2 on 2021-04-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapi', '0002_similarity_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarity',
            name='sample_doc',
        ),
        migrations.RemoveField(
            model_name='similarity',
            name='student_doc',
        ),
        migrations.AddField(
            model_name='similarity',
            name='file',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
