# Generated by Django 3.2 on 2021-04-18 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyapi', '0004_auto_20210418_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarity',
            name='file2',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='similarity',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
