# Generated by Django 3.2 on 2021-04-18 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyapi', '0005_auto_20210418_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
